export default {
  splashVideo: require('./video/splashVideo.mp4'),
  sv: require('./video/sv.mp4'),
  bellIcon: require('./image/bell.png'),
  checkIcon: require('./image/check.png'),
  commentIcon: require('./image/comment.png'),
  threeDotsIcon: require('./image/dots.png'),
  heartIcon: require('./image/heart.png'),
  homeIcon: require('./image/home.png'),
  image1: require('./image/image1.jpg'),
  image2: require('./image/image2.jpg'),
  image3: require('./image/image3.jpg'),
  image4: require('./image/image4.jpg'),
  image5: require('./image/image5.jpg'),
  image6: require('./image/image6.jpg'),
  postIcon: require('./image/post.png'),
  profile1: require('./image/profile1.jpg'),
  profile2: require('./image/profile2.jpg'),
  sendIcon: require('./image/send.png'),
  userIcon: require('./image/user.png'),
};
